package liceosorollab.accesoadatos.entidad;
// default package
// Generated 14-dic-2020 18:49:56 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Artista generated by hbm2java
 */
@Entity
@Table(name = "artista", catalog = "musica", uniqueConstraints = @UniqueConstraint(columnNames = { "discografica_id",
		"name" }))
public class Artista implements java.io.Serializable {

	private int id;
	private Discografica discografica;
	private String name;
	private Set<Album> albums = new HashSet<Album>(0);

	public Artista() {
	}

	public Artista(int id, Discografica discografica, String name) {
		this.id = id;
		this.discografica = discografica;
		this.name = name;
	}

	public Artista(int id, Discografica discografica, String name, Set<Album> albums) {
		this.id = id;
		this.discografica = discografica;
		this.name = name;
		this.albums = albums;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "discografica_id", nullable = false)
	public Discografica getDiscografica() {
		return this.discografica;
	}

	public void setDiscografica(Discografica discografica) {
		this.discografica = discografica;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "artista")
	public Set<Album> getAlbums() {
		return this.albums;
	}

	public void setAlbums(Set<Album> albums) {
		this.albums = albums;
	}

}
