package liceosorollab.accesoadatos.entidad;
// default package
// Generated 14-dic-2020 18:49:56 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Cancion generated by hbm2java
 */
@Entity
@Table(name = "cancion", catalog = "musica", uniqueConstraints = @UniqueConstraint(columnNames = { "album_id",
		"name" }))
public class Cancion implements java.io.Serializable {

	private int id;
	private Album album;
	private String name;
	private double duration;

	public Cancion() {
	}

	public Cancion(int id, Album album, String name, double duration) {
		this.id = id;
		this.album = album;
		this.name = name;
		this.duration = duration;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@JsonBackReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "album_id", nullable = false)
	public Album getAlbum() {
		return this.album;
	}

	public void setAlbum(Album album) {
		this.album = album;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "duration", nullable = false, precision = 22, scale = 0)
	public double getDuration() {
		return this.duration;
	}

	public void setDuration(double duration) {
		this.duration = duration;
	}

}
